### ISSUE TITLE
Sử dụng nó như thế nào?

### ISSUE THREAD

**Issue by markleeit** [htruong/vicat#1]
Anh ơi. Cách sử dụng VieetjCat như thế nào vậy anh. Em chạy nó trên MS-DOS thì hiện thị thông báo lỗi: No file name given.
An xem giúp em  với ạ. Cám ơn  anh.

Ảnh thông báo lỗi: https://i.ibb.co/30J3JLv/Screenshot-2023-03-16-152317.png

**Comment by htruong** [comment]
Em đánh vicat <tên file> ví dụ

vicat file.txt
